<?php

declare(strict_types=1);

namespace Majesko\FpKit\Functions;

/**
 * Transforms each element of an array using the provided function.
 *
 * @param array<mixed> $xs The array to map over
 * @param callable $fn The transformation function to apply to each element
 * @return array<int, mixed>
 */
function map(array $xs, callable $fn): array
{
    return array_map($fn, $xs);
}

/**
 * Filters an array, keeping only elements that satisfy the predicate.
 *
 * Returns a new array with sequential numeric keys (re-indexed).
 *
 * @param array<mixed> $xs The array to filter
 * @param callable $pred The predicate function that determines which elements to keep
 * @return array<int, mixed>
 */
function filter(array $xs, callable $pred): array
{
    // array_values re-indexes the array to have sequential numeric keys
    return array_values(array_filter($xs, $pred));
}

/**
 * Reduces an array to a single value by iteratively applying a function.
 *
 * Starts with an initial value and applies the reducer function to each element,
 * accumulating the result.
 *
 * @param array<mixed> $xs The array to reduce
 * @param mixed $initial The initial accumulator value
 * @param callable $fn The reducer function that takes (accumulator, current) and returns new accumulator
 * @return mixed The final accumulated value
 */
function reduce(array $xs, mixed $initial, callable $fn): mixed
{
    $acc = $initial;

    foreach ($xs as $x) {
        $acc = $fn($acc, $x);
    }

    return $acc;
}

/**
 * Groups array elements by a key generated from each element.
 *
 * Returns an associative array where keys are generated by the key function
 * and values are arrays of elements that share that key.
 *
 * @param array<mixed> $xs The array to group
 * @param callable $keyFn Function that generates a grouping key from each element
 * @return array<string, array<int, mixed>>
 */
function groupBy(array $xs, callable $keyFn): array
{
    $out = [];

    foreach ($xs as $x) {
        $k = (string) $keyFn($x);
        $out[$k][] = $x;
    }

    return $out;
}

/**
 * Indexes array elements by a unique key generated from each element.
 *
 * Returns an associative array where keys are generated by the key function
 * and values are the elements themselves. Later elements with duplicate keys
 * will overwrite earlier ones.
 *
 * @param array<mixed> $xs The array to index
 * @param callable $keyFn Function that generates an index key from each element
 * @return array<string, mixed>
 */
function indexBy(array $xs, callable $keyFn): array
{
    $out = [];

    foreach ($xs as $x) {
        $k = (string) $keyFn($x);
        $out[$k] = $x;
    }

    return $out;
}
